dev: Add initial CODEOWNERS file
elastisys/ck8s-cluster pull request #69
Opened 2020-10-07 08:03 UTC by danielharr

**What this PR does / why we need it**:
Adds an initial CODEOWNERS file based on the discussions at the architecture meeting 2020-10-06.

**Which issue this PR fixes**: -

**Special notes for reviewer**: -

2020-10-07 10:37 UTC, simonklb requested changes
Minor fix, otherwise lgtm!

2020-10-07 10:37 UTC, simonklb commented on CODEOWNERS
> +/cmd/       @simonklb @Xartos
```suggestion
/api/       @simonklb @Xartos
/client/    @simonklb @Xartos
/cmd/       @simonklb @Xartos
```

2020-10-07 11:53 UTC, danielharr commented on CODEOWNERS
> +/cmd/       @simonklb @Xartos
Good catch, added :+1:

2020-10-07 15:39 UTC, simonklb approved these changes

2020-10-08 06:34 UTC, viktor-f approved these changes

2020-10-08 06:35 UTC, merged